export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';

export const GET_LOCATION_ID_REQUEST = 'GET_LOCATION_ID_REQUEST';
export const GET_LOCATION_ID_SUCCESS = 'GET_LOCATION_ID_SUCCESS';
export const GET_LOCATION_ID_ERROR = 'GET_LOCATION_ID_ERROR';
